# This file was generated by GoReleaser. DO NOT EDIT.
cask "mctop" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "7d72062509ab46ba55e8357e82f7f00b44b80246b943b36a71da17a5a248e631"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36e3df237bed8516cd8892d33637da7433811b3c1579b956406c0a6769641adf"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25d53da3745723cab992d798da9e27cf24c3c0b5a7a5dd204113feb135a98069"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef6b84ea00f825955c0baa7c0d6f92e346f655155335938acf8fce897d852034"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_linux_arm64.tar.gz"
    end
  end

  name "mctop"
  desc "A terminal client for MCP servers: explore, call, and CI-test any server."
  homepage "https://github.com/aloki-alok/mctop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mctop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mctop"]
    end
  end

  # No zap stanza required

end
