# This file was generated by GoReleaser. DO NOT EDIT.
cask "mctop" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "41cb60aa9bffb0071dcdfd850b48d87d1637ab42109839c75cd3f6160a3c998e"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbe75c4966ba76567e3346c7069bf8f3827f2a92cb274cdb2f4889f86b98db0d"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ccc4684078088f4e9e0780ac7f201cbb5373f80cbd3a84b81719b5f8323474b"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4a201a3cc00eb32e7f99285dae32931e9ff922a8c9f3fda66e794acf60b1824"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_linux_arm64.tar.gz"
    end
  end

  name "mctop"
  desc "A terminal client for MCP servers: explore, call, and CI-test any server."
  homepage "https://github.com/aloki-alok/mctop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mctop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mctop"]
    end
  end

  # No zap stanza required

end
