# This file was generated by GoReleaser. DO NOT EDIT.
cask "mctop" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "a71943d7a0fde6496e69b7532e693bd33efba4472eede7a7f9b85ff8a350cb74"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85ff4deee021a11e787d7be4182f8e5895fbaed22e452fcfe682229384b1897f"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09671746a84a96689b39e2882fc6d613261d28998c62612df477e770b2b0c4cf"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd3868e9952fd4b08d5e8699c98e7d70b53a788a585cd58f1360545d5a54c02d"
      url "https://github.com/aloki-alok/mctop/releases/download/v#{version}/mctop_linux_arm64.tar.gz"
    end
  end

  name "mctop"
  desc "A terminal client for MCP servers: explore, call, and CI-test any server."
  homepage "https://github.com/aloki-alok/mctop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mctop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mctop"]
    end
  end

  # No zap stanza required

end
